services:
  glassflow:
    image: glassflow/clickhouse-etl-be:stable
    hostname: glassflow
    container_name: flux-glassflow
    depends_on:
      - kafka
      - clickhouse
      - nats
    ports:
      - "8080:8080"
    environment:
      - GLASSFLOW_LOG_FILE_PATH=/tmp/logs/glassflow
      - GLASSFLOW_NATS_SERVER=nats:4222
    networks:
      - flux-net

networks:
  flux-net:
    driver: bridge
